name: Set up CI
description: Install system packages and Ruby with Bundler cache

runs:
  using: composite
  steps:
    - name: Install packages
      shell: bash
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
      with:
        bundler-cache: true
